FORMAT: 1A
HOST: http://127.0.0.1:8000

# kiosk

If you want to change language, add following urls in front of links.

    in Russian [/ru/]
    
    in English [/en/]
    
    in Kyrgyz [/kg/]

## Teacher's schedule [/schedule/teacher/{teacher_id}/]

### List all schedules of teacher_id [GET]

+ Response 200 (application/json)

        [
            {
                "time": 1,
                "day_of_week": 1,
                "subject": {
                    "id": 1,
                    "name": "Math"
                },
                "week": 1,
                "type": 1,
                "teacher": {
                    "id": 1,
                    "name": "Saliev Alisher Borubaevich",
                    "photo": null,
                    "status": "professor",
                    "contact": "email: alisher@mail.ru"
                },
                "classroom": {
                    "id": 1,
                    "name": "301",
                    "floor": 3,
                    "about": "laboratory classroom"
                },
                "group": {
                    "id": 2,
                    "name": "PI(b)1-14",
                    "grade": 2
                }
            },
            {
                "time": 1,
                "day_of_week": 2,
                "subject": {
                    "id": 2,
                    "name": "Programming languages"
                },
                "week": 1,
                "type": 1,
                "teacher": {
                    "id": 1,
                    "name": "Saliev Alisher Borubaevich",
                    "photo": null,
                    "status": "professor",
                    "contact": "email: alisher@mail.ru"
                },
                "classroom": {
                    "id": 1,
                    "name": "301",
                    "floor": 3,
                    "about": "laboratory classroom"
                },
                "group": {
                    "id": 2,
                    "name": "PI(b)1-14",
                    "grade": 2
                }
            },
            {
                "time": 2,
                "day_of_week": 1,
                "subject": {
                    "id": 2,
                    "name": "Programming languages"
                },
                "week": 1,
                "type": 1,
                "teacher": {
                    "id": 1,
                    "name": "Saliev Alisher Borubaevich",
                    "photo": null,
                    "status": "professor",
                    "contact": "email: alisher@mail.ru"
                },
                "classroom": {
                    "id": 1,
                    "name": "301",
                    "floor": 3,
                    "about": "laboratory classroom"
                },
                "group": {
                    "id": 1,
                    "name": "IS(b)1-16",
                    "grade": 1
                }
            }
        ]


## Group schedule [/schedule/group/{group_id}/]

### List all schedules of group_id [GET]

+ Response 200 (application/json)

        [
            {
                "time": 2,
                "day_of_week": 1,
                "subject": {
                    "id": 2,
                    "name": "Programming languages"
                },
                "week": 1,
                "type": 1,
                "teacher": {
                    "id": 1,
                    "name": "Saliev Alisher Borubaevich",
                    "photo": null,
                    "status": "professor",
                    "contact": "email: alisher@mail.ru"
                },
                "classroom": {
                    "id": 1,
                    "name": "301",
                    "floor": 3,
                    "about": "laboratory classroom"
                },
                "group": {
                    "id": 1,
                    "name": "IS(b)1-16",
                    "grade": 1
                }
            },
            {
                "time": 1,
                "day_of_week": 1,
                "subject": {
                    "id": 1,
                    "name": "Math"
                },
                "week": 1,
                "type": 1,
                "teacher": {
                    "id": 2,
                    "name": "Stamkulova Guldana Kubanychbekovna",
                    "photo": null,
                    "status": "teacher",
                    "contact": "phone: +996555444585"
                },
                "classroom": {
                    "id": 1,
                    "name": "301",
                    "floor": 3,
                    "about": "laboratory classroom"
                },
                "group": {
                    "id": 1,
                    "name": "IS(b)1-16",
                    "grade": 1
                }
            }
        ]
        
        
## History [/history/]

### List all histories [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "About KSTU",
                "text": "Some history"
            },
            {
                "id": 2,
                "name": "About KSTU",
                "text": "Other history"
            }
        ]
        
## History [/history/{history_id}/]
### History by id [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "About KSTU",
            "text": "Some history"
        }

## Faculty [/faculty/]
### List all faculties [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "FIT",
                "about": "Some about FIT",
                "departments_of_faculty": [
                    {
                        "id": 1,
                        "name": "POKS",
                        "about": "Some about POKS",
                        "teachers": [
                            {
                                "id": 1,
                                "name": "Saliev Alisher Borubaevich",
                                "photo": null,
                                "status": "professor",
                                "contact": "email: alisher@mail.ru"
                            },
                            {
                                "id": 2,
                                "name": "Stamkulova Guldana Kubanychbekovna",
                                "photo": null,
                                "status": "teacher",
                                "contact": "phone: +996555444585"
                            }
                        ],
                        "groups": [
                            {
                                "id": 1,
                                "name": "IS(b)1-16",
                                "grade": 1
                            },
                            {
                                "id": 2,
                                "name": "PI(b)1-14",
                                "grade": 2
                            }
                        ]
                    }
                ]
            }
        ]

## Faculty [/faculty/{faculty_id}/]
### Faculty by id [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "FIT",
            "about": "Some about FIT",
            "departments_of_faculty": [
                {
                    "id": 1,
                    "name": "POKS",
                    "about": "Some about POKS",
                    "teachers": [
                        {
                            "id": 1,
                            "name": "Saliev Alisher Borubaevich",
                            "photo": null,
                            "status": "professor",
                            "contact": "email: alisher@mail.ru"
                        },
                        {
                            "id": 2,
                            "name": "Stamkulova Guldana Kubanychbekovna",
                            "photo": null,
                            "status": "teacher",
                            "contact": "phone: +996555444585"
                        }
                    ],
                    "groups": [
                        {
                            "id": 1,
                            "name": "IS(b)1-16",
                            "grade": 1
                        },
                        {
                            "id": 2,
                            "name": "PI(b)1-14",
                            "grade": 2
                        }
                    ]
                }
            ]
        }
        
        
## Institute [/institute/]
### List all institutes [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "IAT",
                "about": "Some about IAT",
                "departments_of_institute": [
                    {
                        "id": 2,
                        "name": "PMI",
                        "about": "Some about PMI",
                        "teachers": [
                            {
                                "id": 1,
                                "name": "Saliev Alisher Borubaevich",
                                "photo": null,
                                "status": "professor",
                                "contact": "email: alisher@mail.ru"
                            },
                            {
                                "id": 2,
                                "name": "Stamkulova Guldana Kubanychbekovna",
                                "photo": null,
                                "status": "teacher",
                                "contact": "phone: +996555444585"
                            }
                        ],
                        "groups": [
                            {
                                "id": 1,
                                "name": "IS(b)1-16",
                                "grade": 1
                            },
                            {
                                "id": 2,
                                "name": "PI(b)1-14",
                                "grade": 2
                            }
                        ]
                    }
                ]
            }
        ]

## Institute [/institute/{institute_id}/]
### Institute by id [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "IAT",
            "about": "Some about IAT",
            "departments_of_institute": [
                {
                    "id": 2,
                    "name": "PMI",
                    "about": "Some about PMI",
                    "teachers": [
                            {
                                "id": 1,
                                "name": "Saliev Alisher Borubaevich",
                                "photo": null,
                                "status": "professor",
                                "contact": "email: alisher@mail.ru"
                            },
                            {
                                "id": 2,
                                "name": "Stamkulova Guldana Kubanychbekovna",
                                "photo": null,
                                "status": "teacher",
                                "contact": "phone: +996555444585"
                            }
                    ],
                    "groups": [
                        {
                            "id": 1,
                            "name": "IS(b)1-16",
                            "grade": 1
                        },
                        {
                            "id": 2,
                            "name": "PI(b)1-14",
                            "grade": 2
                        }
                    ]
                }
            ]
        }
        
## Department [/department/]
### List of departments [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "POKS",
                "about": "Some about POKS",
                "teachers": [
                    {
                        "id": 1,
                        "name": "Saliev Alisher Borubaevich",
                        "photo": null,
                        "status": "professor",
                        "contact": "email: alisher@mail.ru"
                    },
                    {
                        "id": 2,
                        "name": "Stamkulova Guldana Kubanychbekovna",
                        "photo": null,
                        "status": "teacher",
                        "contact": "phone: +996555444585"
                    }
                ],
                "groups": [
                    {
                        "id": 1,
                        "name": "IS(b)1-16",
                        "grade": 1
                    },
                    {
                        "id": 2,
                        "name": "PI(b)1-14",
                        "grade": 2
                    }
                ]
            },
            {
                "id": 2,
                "name": "PMI",
                "about": "Some about PMI",
                "teachers": [
                    {
                        "id": 1,
                        "name": "Saliev Alisher Borubaevich",
                        "photo": null,
                        "status": "professor",
                        "contact": "email: alisher@mail.ru"
                    },
                    {
                        "id": 2,
                        "name": "Stamkulova Guldana Kubanychbekovna",
                        "photo": null,
                        "status": "teacher",
                        "contact": "phone: +996555444585"
                    }
                ],
                "groups": [
                    {
                        "id": 1,
                        "name": "IS(b)1-16",
                        "grade": 1
                    },
                    {
                        "id": 2,
                        "name": "PI(b)1-14",
                        "grade": 2
                    }
                ]
            }
        ]
        

## Department [/department/{department_id}/]
### Department by id [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "POKS",
            "about": "Some about POKS",
            "teachers": [
                {
                    "id": 1,
                    "name": "Saliev Alisher Borubaevich",
                    "photo": null,
                    "status": "professor",
                    "contact": "email: alisher@mail.ru"
                },
                {
                    "id": 2,
                    "name": "Stamkulova Guldana Kubanychbekovna",
                    "photo": null,
                    "status": "teacher",
                    "contact": "phone: +996555444585"
                }
            ],
            "groups": [
                {
                    "id": 1,
                    "name": "IS(b)1-16",
                    "grade": 1
                },
                {
                    "id": 2,
                    "name": "PI(b)1-14",
                    "grade": 2
                }
            ]
        }


## Building [/building/]
### List of buildings [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "#1",
                "location": "empty",
                "floor": 4,
                "classrooms": [
                    {
                        "id": 1,
                        "name": "301",
                        "floor": 3,
                        "about": "laboratory classroom"
                    }
                ]
            }
        ]

## Classroom [/classroom/]
### List of classrooms [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "301",
                "floor": 3,
                "about": "laboratory classroom"
            }
        ]



## Group [/group/]
### List of groups [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "IS(b)1-16",
                "grade": 1
            },
            {
                "id": 2,
                "name": "PI(b)1-14",
                "grade": 2
            }
        ]
        
## Teacher [/teacher/]
### List of teachers [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Saliev Alisher Borubaevich",
                "photo": null,
                "status": "professor",
                "contact": "email: alisher@mail.ru"
            },
            {
                "id": 2,
                "name": "Stamkulova Guldana Kubanychbekovna",
                "photo": null,
                "status": "teacher",
                "contact": "phone: +996555444585"
            }
        ]
        
## Preuniversity [/preuniversity/]
### List of preuniversities [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "lyceum",
                "about": "Some about lyceum"
            }
        ]