# Generated by Django 2.2 on 2019-07-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleOfGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '8:00-9:20'), (2, '9:30-10:50'), (3, '11:00-12:20'), (4, '13:00-14:20'), (5, '14:30-15:50'), (6, '16:00-17:20')], default=1)),
                ('day_of_week', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ')], default=1)),
                ('week', models.IntegerField(choices=[(1, 'Числ'), (2, 'Знам')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Лк'), (2, 'Пр'), (3, 'Лб')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOfTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '8:00-9:20'), (2, '9:30-10:50'), (3, '11:00-12:20'), (4, '13:00-14:20'), (5, '14:30-15:50'), (6, '16:00-17:20')], default=1)),
                ('day_of_week', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ')], default=1)),
                ('week', models.IntegerField(choices=[(1, 'Числ'), (2, 'Знам')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'Лк'), (2, 'Пр'), (3, 'Лб')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('schedule_of_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_for_group', to='schedule.ScheduleOfGroup')),
                ('schedule_of_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_for_teacher', to='schedule.ScheduleOfTeacher')),
            ],
        ),
    ]
