# Generated by Django 2.2 on 2019-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
