# Generated by Django 2.2.3 on 2019-07-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='type',
        ),
        migrations.AddField(
            model_name='schedule',
            name='type_of_lecture',
            field=models.IntegerField(choices=[(1, 'Лк'), (2, 'Пр'), (3, 'Лб')], default=1, verbose_name='Type of lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='university.Classroom', verbose_name='Classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ')], default=1, verbose_name='Day of the week'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schedule.Subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='university.Teacher', verbose_name='Teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.IntegerField(choices=[(1, '8:00-9:20'), (2, '9:30-10:50'), (3, '11:00-12:20'), (4, '13:00-14:20'), (5, '14:30-15:50'), (6, '16:00-17:20')], default=1, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.IntegerField(choices=[(1, 'Числ'), (2, 'Знам')], default=1, verbose_name='Week'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
