# Generated by Django 2.2 on 2019-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default=1, verbose_name='Day of the week'),
        ),
    ]
