# Generated by Django 2.2 on 2019-07-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_subject_name_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name_ru',
        ),
    ]
