# Generated by Django 2.2 on 2019-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_subject_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
