# Generated by Django 2.2 on 2019-07-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190717_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
    ]
