# Generated by Django 2.2 on 2019-07-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name_kg',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='history',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='history',
            name='text_kg',
        ),
        migrations.RemoveField(
            model_name='history',
            name='text_ru',
        ),
    ]
