# Generated by Django 2.2 on 2019-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190717_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='history',
            name='name_kg',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='history',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='history',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='history',
            name='text_kg',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
