# Generated by Django 2.2 on 2019-07-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190716_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='history',
            name='text_ru',
        ),
    ]
