# Generated by Django 2.2 on 2019-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190716_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
