# Generated by Django 2.2 on 2019-07-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='grade_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='grade_kg',
        ),
        migrations.RemoveField(
            model_name='group',
            name='grade_ru',
        ),
    ]
