# Generated by Django 2.2 on 2019-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='about_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name_kg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='about_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='about_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_kg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='about_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='about_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='name_kg',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_kg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status_kg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
