# Generated by Django 2.2.3 on 2019-07-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floor',
            field=models.PositiveIntegerField(verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='about',
            field=models.CharField(max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='university.Building', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.PositiveIntegerField(verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_of_faculty', to='university.Faculty', verbose_name='Faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments_of_institute', to='university.Institute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='university.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
    ]
