# Generated by Django 2.2 on 2019-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190717_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='building',
            name='location_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='building',
            name='location_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='about_en',
            field=models.CharField(max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='about_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='about_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name_kg',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='department',
            name='about_kg',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='department',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='about_kg',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_kg',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='institute',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='institute',
            name='about_kg',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='institute',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='about_en',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='about_kg',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='name_kg',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status_kg',
            field=models.CharField(max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Status'),
        ),
    ]
