# Generated by Django 2.2 on 2019-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190725_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='about',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='about_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='about_kg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='about_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_kg',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='department',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_kg',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about_kg',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='about_kg',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='preuniversity',
            name='about_ru',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
