# Generated by Django 2.2 on 2019-07-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20190716_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location_ru',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='department',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='preuniversity',
            name='about_ru',
        ),
        migrations.RemoveField(
            model_name='preuniversity',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contact_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='status_ru',
        ),
    ]
