# Generated by Django 2.2 on 2019-07-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190717_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.RemoveField(
            model_name='building',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='building',
            name='location_kg',
        ),
        migrations.RemoveField(
            model_name='building',
            name='location_ru',
        ),
        migrations.AddField(
            model_name='group',
            name='grade_en',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='group',
            name='grade_kg',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='group',
            name='grade_ru',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, verbose_name='Grade'),
        ),
    ]
