# Generated by Django 2.2 on 2019-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20190716_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='location_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='about_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preuniversity',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
